python prune.py --data-path data/imagenet \
    --model resnet152.tv_in1k \
    --pruning-type taylor \
    --pruning-ratio 0.40 \
    --train-batch-size 64 \
    --val-batch-size 64 \
    --global-pruning \
    --taylor-batchs 100 \
    --save-as output/pruned/resnet152_4.0G.pth  \
    --val-resize 256 \
    --interpolation bilinear \
    --round-to 2 \
    --drop 0.1 